[build]
  publish = "dist"
  command = "yarn build"

[context.production]
  [context.production.environment]
    APP_ENV="production"
    NODE_ENV="production"
    YARN_FLAGS="--production=false"
    YARN_VERSION="1.3.2"
