[build]
  publish = "dist"
  command = "yarn build"

[context.production]
  [context.production.environment]
    API_BASE_URL="https://workouts-tracker.herokuapp.com"
    APP_ENV="production"
    NODE_ENV="production"
    YARN_FLAGS="--production=false"
    YARN_VERSION="1.9.4"
