// Exercises action types.
export const FETCH_EXERCISES = 'FETCH_EXERCISES'
export const FETCH_EXERCISES_FAIL = 'FETCH_EXERCISES_FAIL'
export const FETCH_EXERCISES_SUCCESS = 'FETCH_EXERCISES_SUCCESS'
export const REQUEST_SAVE_EXERCISE = 'REQUEST_SAVE_EXERCISE'
export const REQUEST_SAVE_EXERCISE_FAIL = 'REQUEST_SAVE_EXERCISE_FAIL'
export const REQUEST_SAVE_EXERCISE_SET = 'REQUEST_SAVE_EXERCISE_SET'
export const REQUEST_SAVE_EXERCISE_SET_FAIL = 'REQUEST_SAVE_EXERCISE_SET_FAIL'
export const REQUEST_SAVE_EXERCISE_SET_SUCCESS =
  'REQUEST_SAVE_EXERCISE_SET_SUCCESS'
export const REQUEST_SAVE_EXERCISE_SUCCESS = 'REQUEST_SAVE_EXERCISE_SUCCESS'

// Modal action types.
export const CLOSE_MODAL = 'CLOSE_MODAL'
export const OPEN_MODAL = 'OPEN_MODAL'

// User action types.
export const LOG_OUT = 'LOG_OUT'

// Weight action types.
export const FETCH_WEIGHT = 'FETCH_WEIGHT'
export const FETCH_WEIGHT_FAIL = 'FETCH_WEIGHT_FAIL'
export const FETCH_WEIGHT_SUCCESS = 'FETCH_WEIGHT_SUCCESS'
export const REQUEST_SAVE_WEIGHT = 'REQUEST_SAVE_WEIGHT'
export const REQUEST_SAVE_WEIGHT_FAIL = 'REQUEST_SAVE_WEIGHT_FAIL'
export const REQUEST_SAVE_WEIGHT_SUCCESS = 'REQUEST_SAVE_WEIGHT_SUCCESS'
